[project]
name = "bicfit"
version = "0.1.0"
description = "General purpose exponential function fitting"
requires-python = ">=3.11"
dependencies = [
    "matplotlib",
    "notebook>=7.4.5",
    "numpy",
    "scipy>=1.10.0",
]

[project.optional-dependencies]
dev = [
    "ruff>=0.8",
    "pytest>=8.0",
    "pytest-ordering",
    "pytest-sugar",
    "pytest-xdist",
]
