name: "Publish"

on:
  push:
    tags:
      # Publish on any tag starting with a `v`, e.g., v0.1.0
      - v*

jobs:
  run:
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install Python 3.10
        run: uv python install 3.10
      - name: Build
        run: uv build
      - name: Test
        run:  uv run --isolated --no-project --python=3.10 --with dist/*.whl pytest .
      - name: Publish
        run: uv publish
